### ISSUE TITLE
mu-law encoded data: ValueError: [(128, -128), (0, 0)] cannot contain negative values.

### ISSUE THREAD

**Issue by jseplae** [r9y9/wavenet_vocoder#127]
Hi,

I'm not sure if this is a bug (likely something on my side), but given the same json used for both pre-processing and training, I get this padding issue.

> {'--checkpoint': None,
 '--checkpoint-dir': 'checkpoints',
 '--data-root': 'xxx',
 '--help': False,
 '--hparams': '',
 '--log-event-path': None,
 '--preset': 'presets/xxx.json',
 '--reset-optimizer': False,
 '--restore-parts': None,
 '--speaker-id': None}
Hyperparameters:
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1e-08
  allow_clipping_in_normalization: True
  amsgrad: False
  batch_size: 1
  builder: wavenet
  checkpoint_interval: 10000
  cin_channels: 80
  clip_thresh: -1
  dropout: 0.050000000000000044
  ema_decay: 0.9999
  exponential_moving_average: False
  fft_size: 1024
  fmax: 7600
  fmin: 125
  frame_shift_ms: None
  freq_axis_kernel_size: 3
  gate_channels: 512
  gin_channels: 16
  hop_size: 256
  initial_learning_rate: 0.001
  input_type: mulaw-quantize
  kernel_size: 3
  layers: 24
  legacy: True
  log_scale_min: -32.23619130191664
  lr_schedule: noam_learning_rate_decay
  lr_schedule_kwargs: {}
  max_time_sec: None
  max_time_steps: 8000
  min_level_db: -100
  n_speakers: 12
  name: wavenet_vocoder
  nepochs: 2000
  num_mels: 80
  num_workers: 8
  out_channels: 256
  pin_memory: True
  quantize_channels: 256
  random_state: 1234
  ref_level_db: 20
  rescaling: True
  rescaling_max: 0.999
  residual_channels: 512
  sample_rate: 16000
  save_optimizer_state: True
  silence_threshold: 2
  skip_out_channels: 256
  stacks: 4
  test_eval_epoch_interval: 5
  test_num_samples: None
  test_size: 0.0441
  train_eval_interval: 10000
  upsample_conditional_features: True
  upsample_scales: [4, 4, 4, 4]
  weight_decay: 0.0
  weight_normalization: True
Local conditioning enabled. Shape of a sample: (8657, 80).
[train]: length of the dataset is 1147
Speaker stats: {8: 93, 10: 92, 11: 93, 6: 97, 9: 98, 5: 99, 4: 98, 1: 95, 7: 94, 2: 94, 3: 95, 0: 99}
Local conditioning enabled. Shape of a sample: (9669, 80).
[test]: length of the dataset is 53
Speaker stats: {7: 6, 11: 7, 8: 7, 3: 5, 1: 5, 2: 6, 10: 8, 4: 2, 6: 3, 9: 2, 5: 1, 0: 1}
Receptive field (samples / ms): 505 / 31.5625
TensorBoard event log path: log/run-test2018-10-31_10:25:24.107170
/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
0it [00:00, ?it/s]Saved checkpoint: checkpoints/checkpoint_step000000000.pth
Traceback (most recent call last):
  File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 976, in <module>
    checkpoint_dir=checkpoint_dir)
  File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 706, in train_loop
    for step, (x, y, c, g, input_lengths) in tqdm(enumerate(data_loader)):
  File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 423, in collate_fn
    max_input_len, padding_value) for x in batch], dtype=np.float32)
  File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 423, in <listcomp>
    max_input_len, padding_value) for x in batch], dtype=np.float32)
  File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 95, in _pad_2d
    mode="constant", constant_values=constant_values)
  File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1200, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 985, in _validate_lengths
    raise ValueError(fmt % (number_elements,))
ValueError: [(128, -128), (0, 0)] cannot contain negative values.

**Comment by r9y9** [comment]
Thanks for the report. There's small bug in #123. I have a fix locally and try to push it later today.

**Comment by jseplae** [comment]
Thanks for the quick response. I will test again after the fix.

**Comment by jseplae** [comment]
> 
> 
> Fixed. Feel free to reopen if the problem persists.

Awesome. Thanks!

**Comment by Laverga123** [comment]
> Hi,
> 
> I'm not sure if this is a bug (likely something on my side), but given the same json used for both pre-processing and training, I get this padding issue.
> 
> > {'--checkpoint': None,
>  '--checkpoint-dir': 'checkpoints',
>  '--data-root': 'xxx',
>  '--help': False,
>  '--hparams': '',
>  '--log-event-path': None,
>  '--preset': 'presets/xxx.json',
>  '--reset-optimizer': False,
>  '--restore-parts': None,
>  '--speaker-id': None}
> Hyperparameters:
>   adam_beta1: 0.9
>   adam_beta2: 0.999
>   adam_eps: 1e-08
>   allow_clipping_in_normalization: True
>   amsgrad: False
>   batch_size: 1
>   builder: wavenet
>   checkpoint_interval: 10000
>   cin_channels: 80
>   clip_thresh: -1
>   dropout: 0.050000000000000044
>   ema_decay: 0.9999
>   exponential_moving_average: False
>   fft_size: 1024
>   fmax: 7600
>   fmin: 125
>   frame_shift_ms: None
>   freq_axis_kernel_size: 3
>   gate_channels: 512
>   gin_channels: 16
>   hop_size: 256
>   initial_learning_rate: 0.001
>   input_type: mulaw-quantize
>   kernel_size: 3
>   layers: 24
>   legacy: True
>   log_scale_min: -32.23619130191664
>   lr_schedule: noam_learning_rate_decay
>   lr_schedule_kwargs: {}
>   max_time_sec: None
>   max_time_steps: 8000
>   min_level_db: -100
>   n_speakers: 12
>   name: wavenet_vocoder
>   nepochs: 2000
>   num_mels: 80
>   num_workers: 8
>   out_channels: 256
>   pin_memory: True
>   quantize_channels: 256
>   random_state: 1234
>   ref_level_db: 20
>   rescaling: True
>   rescaling_max: 0.999
>   residual_channels: 512
>   sample_rate: 16000
>   save_optimizer_state: True
>   silence_threshold: 2
>   skip_out_channels: 256
>   stacks: 4
>   test_eval_epoch_interval: 5
>   test_num_samples: None
>   test_size: 0.0441
>   train_eval_interval: 10000
>   upsample_conditional_features: True
>   upsample_scales: [4, 4, 4, 4]
>   weight_decay: 0.0
>   weight_normalization: True
> Local conditioning enabled. Shape of a sample: (8657, 80).
> [train]: length of the dataset is 1147
> Speaker stats: {8: 93, 10: 92, 11: 93, 6: 97, 9: 98, 5: 99, 4: 98, 1: 95, 7: 94, 2: 94, 3: 95, 0: 99}
> Local conditioning enabled. Shape of a sample: (9669, 80).
> [test]: length of the dataset is 53
> Speaker stats: {7: 6, 11: 7, 8: 7, 3: 5, 1: 5, 2: 6, 10: 8, 4: 2, 6: 3, 9: 2, 5: 1, 0: 1}
> Receptive field (samples / ms): 505 / 31.5625
> TensorBoard event log path: log/run-test2018-10-31_10:25:24.107170
> /home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
>   warnings.warn(warning.format(ret))
> 0it [00:00, ?it/s]Saved checkpoint: checkpoints/checkpoint_step000000000.pth
> Traceback (most recent call last):
>   File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 976, in <module>
>     checkpoint_dir=checkpoint_dir)
>   File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 706, in train_loop
>     for step, (x, y, c, g, input_lengths) in tqdm(enumerate(data_loader)):
>   File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__
>     for obj in iterable:
>   File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
>     return self._process_next_batch(batch)
>   File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> ValueError: Traceback (most recent call last):
>   File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 423, in collate_fn
>     max_input_len, padding_value) for x in batch], dtype=np.float32)
>   File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 423, in <listcomp>
>     max_input_len, padding_value) for x in batch], dtype=np.float32)
>   File "/home/xxx/PyCharm-remote/wavenet-vocoder/train.py", line 95, in _pad_2d
>     mode="constant", constant_values=constant_values)
>   File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 1200, in pad
>     pad_width = _validate_lengths(narray, pad_width)
>   File "/home/xxx/miniconda3/envs/wavenet-vocoder/lib/python3.6/site-packages/numpy/lib/arraypad.py", line 985, in _validate_lengths
>     raise ValueError(fmt % (number_elements,))
> ValueError: [(128, -128), (0, 0)] cannot contain negative values.
