### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,513) (0,) 

### ISSUE THREAD

**Issue by Eurus-Holmes** [r9y9/wavenet_vocoder#147]
When I run [Online TTS demo](https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb) on colab,
in the section `Mel-spectrogram prediction by Tacoron2`
afterI running this code:

```
# Remove old files if exist
! rm -rf tacotron_output
! python synthesize.py --model='Tacotron' --mode='eval' \
  --hparams='symmetric_mels=False,max_abs_value=4.0,power=1.1,outputs_per_step=1' \
  --text_list=./text_list.txt
```

the ValueError occurred:

```
loaded model at logs-Tacotron/pretrained/model.ckpt-189500
Hyperparameters:
  allow_clipping_in_normalization: True
  attention_dim: 128
  attention_filters: 32
  attention_kernel: (31,)
  cleaners: english_cleaners
  cumulative_weights: True
  decoder_layers: 2
  decoder_lstm_units: 1024
  embedding_dim: 512
  enc_conv_channels: 512
  enc_conv_kernel_size: (5,)
  enc_conv_num_layers: 3
  encoder_lstm_units: 256
  fft_size: 1024
  fmax: 7600
  fmin: 125
  frame_shift_ms: None
  griffin_lim_iters: 60
  hop_size: 256
  impute_finished: False
  input_type: raw
  log_scale_min: -32.23619130191664
  mask_encoder: False
  mask_finished: False
  max_abs_value: 4.0
  max_iters: 2500
  min_level_db: -100
  num_freq: 513
  num_mels: 80
  outputs_per_step: 1
  postnet_channels: 512
  postnet_kernel_size: (5,)
  postnet_num_layers: 5
  power: 1.1
  predict_linear: False
  prenet_layers: [256, 256]
  quantize_channels: 65536
  ref_level_db: 20
  rescale: True
  rescaling_max: 0.999
  sample_rate: 22050
  signal_normalization: True
  silence_threshold: 2
  smoothing: False
  stop_at_any: True
  symmetric_mels: False
  tacotron_adam_beta1: 0.9
  tacotron_adam_beta2: 0.999
  tacotron_adam_epsilon: 1e-06
  tacotron_batch_size: 16
  tacotron_decay_learning_rate: True
  tacotron_decay_rate: 0.4
  tacotron_decay_steps: 50000
  tacotron_dropout_rate: 0.5
  tacotron_final_learning_rate: 1e-05
  tacotron_initial_learning_rate: 0.001
  tacotron_reg_weight: 1e-06
  tacotron_scale_regularization: True
  tacotron_start_decay: 50000
  tacotron_teacher_forcing_ratio: 1.0
  tacotron_zoneout_rate: 0.1
  trim_silence: True
  use_lws: True
Constructing model: Tacotron
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/rnn.py:417: calling reverse_sequence (from tensorflow.python.ops.array_ops) with seq_dim is deprecated and will be removed in a future version.
Instructions for updating:
seq_dim is deprecated, use seq_axis instead
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py:432: calling reverse_sequence (from tensorflow.python.ops.array_ops) with batch_dim is deprecated and will be removed in a future version.
Instructions for updating:
batch_dim is deprecated, use batch_axis instead
Initialized Tacotron model. Dimensions (? = dynamic shape): 
  embedding:                (1, ?, 512)
  enc conv out:             (1, ?, 512)
  encoder out:              (1, ?, 512)
  decoder out:              (?, ?, 80)
  residual out:             (?, ?, 512)
  projected residual out:   (?, ?, 80)
  mel out:                  (?, ?, 80)
  <stop_token> out:         (?, ?)
Loading checkpoint: logs-Tacotron/pretrained/model.ckpt-189500
  0% 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "synthesize.py", line 34, in <module>
    main()
  File "synthesize.py", line 28, in main
    tacotron_synthesize(args)
  File "/root/Tacotron-2/tacotron/synthesize.py", line 81, in tacotron_synthesize
    run_eval(args, checkpoint_path, output_dir, sentences)
  File "/root/Tacotron-2/tacotron/synthesize.py", line 27, in run_eval
    mel_filename = synth.synthesize(text, i+1, eval_dir, log_dir, None)
  File "/root/Tacotron-2/tacotron/synthesizer.py", line 63, in synthesize
    wav = audio.inv_mel_spectrogram(mels.T)
  File "/root/Tacotron-2/datasets/audio.py", line 86, in inv_mel_spectrogram
    S = _mel_to_linear(_db_to_amp(D + hparams.ref_level_db))  # Convert back to linear
  File "/root/Tacotron-2/datasets/audio.py", line 142, in _mel_to_linear
    _inv_mel_basis = np.linalg.pinv(_build_mel_basis())
  File "/root/Tacotron-2/datasets/audio.py", line 148, in _build_mel_basis
    fmin=hparams.fmin, fmax=hparams.fmax)
  File "/usr/local/lib/python3.6/dist-packages/librosa/filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,513) (0,) 
```

**Comment by r9y9** [comment]
Did you follow a suggession by https://github.com/r9y9/wavenet_vocoder/issues/146#issuecomment-483563931?

**Comment by r9y9** [comment]
See also https://github.com/librosa/librosa/issues/826. I don't think this is a bug of our code.

**Comment by r9y9** [comment]
I will fix the notebook to avoid the error. Once I have a fix, I will close this issue.

**Comment by Eurus-Holmes** [comment]
@r9y9 hi, thanks for your help! I have fixed this error after update the librosa version to 0.6.2, 
[Tacotron2 and WaveNet  text-to-speech demo.ipynb](https://colab.research.google.com/drive/1opGd1dPbAbTtghH_b3aF7ujfKdVMBCPE)

**Comment by r9y9** [comment]
Fixed by https://github.com/r9y9/Colaboratory/commit/d83d15bd87bbe1b6fbecab302cb7b60b3294dc6e

**Comment by Eurus-Holmes** [comment]
@r9y9 Thanks for your work!
