### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by wangdory** [r9y9/wavenet_vocoder#150]
Hi, an error occurred during training conditioned on mel-spectrogram.
My system is an IBM powerAI with a tesla v100 gpu.
The following are the software version I used.
 CUDA = 10.0
tensorflow = v1.12.0
python 3.6
pytroch = 1.0.0

The command input are
 python train.py --data-root=./data/BZNSYP/ --speaker-id=0 -- hparams="cin_channels=80,gin_channels=-1"

The error message I got are as follows:
### 
        0it [00:00, ?it/s]/opt/DL/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1120:UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
	warning.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
        1007it [05.46, 2.92it/s]Saved checkpoints/checkpoint_step000001007.pth
        Traceback (most recent call last):
	    File "train.py", line 978, in <module>
		checkpoint_dir=checkpoint_dir)
	    File "train.py", line 707, in train_loop
		for step, (x, y, c, g, input_lengths) in tqdm(enumerate(data_loader)):
	    File "/opt/anaconda3/envs/wavenet_vocoder1/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in__iter__
		for obj in iterable:
	    File "/opt/DL/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
		return self._process_next_batch(batch)
	    File "/opt/DL/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
		raise batch.exc_type(batch.exc_msg)
    RuntimeError: Traceback (most recent call last):
	    File "/opt/DL/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
		samples = collate_fn([dataset[i] for i in bath_indices])
	    File "/opt/DL/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
		samples = collate_fn([dataset[i] for i in bath_indices])
	    File "train.py", line 243, in __getitem__
		mel = self.Mel[idx]
	File "/opt/anaconda3/envs/wavenet_vocoder1/lib/python3.6/site-packages/nnmnkwii/datasets/__init__.py", line	145, in __getitem__
		paths = self.collected_files[idx]
	File "/opt/DL/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 443, in __array__	
		return self.numpy()
     RuntimeError: storage_.data() || numel_ == 0 ASSERT FAILED at /home/builder/build/pytorch/powerai-build/pytorch/aten/src/ATen/core/TensorImpl.h:271, please report a bug to PyTorch.
    The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.

Is there any way to solve it? Thank you.

**Comment by r9y9** [comment]
As the error message saying, please report a bug to PyTorch.
