### ISSUE TITLE
Tkinter's PhotoImage methods and Thread Safety?

### ISSUE THREAD

**Issue by SvenShade** [r9y9/wavenet_vocoder#20]
Hi guys! Fantastic work with this implementation.

Hopefully a quick question today; all was training fine over LJSpeech, until 16k steps or so, when this error was thrown.

```
Save intermediate states at step 10000
Saved checkpoint: checkpoints/checkpoint_step000010000.pth
Saved averaged checkpoint: checkpoints/checkpoint_step000010000_ema.pth
Using averaged model for evaluation
Shape of local conditioning features: torch.Size([1, 80, 31])
Intial value: 0.0
6261it [1:11:40,  1.46it/s]
[train] Loss: 69.05194234611926█████████████| 7936/7936 [02:39<00:00, 49.77it/s]
289it [01:11,  4.05it/s]
[test] Loss: 66.40849115444303
4871it [55:02,  1.47it/s]Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7f409809d160>>
Traceback (most recent call last):
  File "/home/sven/anaconda2/envs/py36/lib/python3.6/tkinter/__init__.py", line 3501, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
Traceback (most recent call last):
  File "/home/sven/anaconda2/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/home/sven/anaconda2/envs/py36/lib/python3.6/multiprocessing/connection.py", line 455, in accept
    deliver_challenge(c, self._authkey)
  File "/home/sven/anaconda2/envs/py36/lib/python3.6/multiprocessing/connection.py", line 722, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/sven/anaconda2/envs/py36/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/sven/anaconda2/envs/py36/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/sven/anaconda2/envs/py36/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Aborted (core dumped)
```

I've kept in some of the former prints to help contextualise the first error (the exception in tkinter).
I feel rather out of my depth trying to debug this, as I'm not sure where to begin. Is this something people have encountered before?

Thanks :)

**Comment by mdda** [comment]
FWIW : I've also seen this error from tkinter w.r.t.  PhotoImage objects and threads, running on the command line in Fedora 27, Python 3.6 (tkinter in system packages, rather than the env).

**Comment by SvenShade** [comment]
Thanks. Yeah, it's surely something to do with tkinter not being thread-safe with those PhotoImage methods. Dunno what to do about that though xD

**Comment by r9y9** [comment]
Likely there’s a problem in matplotlib backend. Can you try https://github.com/r9y9/wavenet_vocoder/issues/9#issuecomment-359342322 and see if it works?

**Comment by SvenShade** [comment]
So far so good! I'll let it run overnight to be sure.

**Comment by r9y9** [comment]
Should be fixed by https://github.com/r9y9/wavenet_vocoder/pull/21

**Comment by SvenShade** [comment]
Yep, I believe so.
