### ISSUE TITLE
Can't load data 

### ISSUE THREAD

**Issue by RussellSB** [r9y9/wavenet_vocoder#212]
Hi! I keep getting this error:

```
  warn("No files are collected. You might have specified wrong data source.")
mel <nnmnkwii.datasets.FileSourceDataset object at 0x7f67405619a0>
Traceback (most recent call last):
  File "train.py", line 1071, in <module>
    data_loaders = get_data_loaders(dump_root, speaker_id, test_shuffle=True)
  File "train.py", line 996, in get_data_loaders
    Mel[0].shape))
  File "/homes/rs002/.local/lib/python3.8/site-packages/nnmnkwii/datasets/__init__.py", line 145, in __getitem__
    paths = self.collected_files[idx]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I did try fixing it following the resolution to this issue https://github.com/r9y9/nnmnkwii/issues/65 but it still does not work

**Comment by RussellSB** [comment]
Hi all, browsing issues some more it seems like the solution is to simply stick to the recipes https://github.com/r9y9/wavenet_vocoder/issues/196
