### ISSUE TITLE
librosa error on stage 2 of gaussian run.sh ParameterError: Audio data must be floating-point

### ISSUE THREAD

**Issue by Barigamb738** [r9y9/wavenet_vocoder#217]
This is the error i'm getting.
C:\Users\fille\Documents\GitHub\wavenet_vocoder\audio.py:38: FutureWarning: Pass orig_sr=44100, target_sr=22050 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  x = librosa.resample(x, sr, hparams.sample_rate)
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\fille\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\fille\Documents\GitHub\wavenet_vocoder\datasets\wavallin.py", line 31, in _process_utterance
    wav = audio.load_wav(wav_path)
  File "C:\Users\fille\Documents\GitHub\wavenet_vocoder\audio.py", line 38, in load_wav
    x = librosa.resample(x, sr, hparams.sample_rate)
  File "C:\Users\fille\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "C:\Users\fille\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py", line 576, in resample
    util.valid_audio(y, mono=False)
  File "C:\Users\fille\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\fille\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\utils.py", line 275, in valid_audio
    raise ParameterError("Audio data must be floating-point")
librosa.util.exceptions.ParameterError: Audio data must be floating-point
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/fille/Documents/GitHub/wavenet_vocoder/egs/gaussian/../..//preprocess.py", line 71, in <module>
    preprocess(mod, in_dir, out_dir, num_workers)
  File "C:/Users/fille/Documents/GitHub/wavenet_vocoder/egs/gaussian/../..//preprocess.py", line 24, in preprocess
    metadata = mod.build_from_path(in_dir, out_dir, num_workers, tqdm=tqdm)
  File "C:\Users\fille\Documents\GitHub\wavenet_vocoder\datasets\wavallin.py", line 26, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "C:\Users\fille\Documents\GitHub\wavenet_vocoder\datasets\wavallin.py", line 26, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "C:\Users\fille\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\fille\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
librosa.util.exceptions.ParameterError: Audio data must be floating-point

What do I do?

This is the logs before:
$ sh ./egs/gaussian/run.sh --stage 0 --stop-stage 2
stage 0: train/dev/eval split
Total number of utterances: 1367
130it [00:00, 1297.74it/s]Total hours 0.201 exceeded limit (0.2 hours).
226it [00:00, 1385.03it/s]
Total number of collected utterances: 227
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 207/207 [00:01<00:00, 185.37it/s] 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 146.81it/s] 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 153.85it/s] 
Waveform min: [-2.14748365e+09]
Waveform max: [2.14741811e+09]
Waveform absolute max: 2147483648.0
There were clipping(s) in your dataset.
Global scaling factor would be around 4.656612873077393e-10
Train/dev/test split:
train_no_dev: 0.18 hours (207 utt)
dev: 0.01 hours (10 utt)
eval: 0.01 hours (10 utt)
stage 1: Feature Generation
Sampling frequency: 22050
  0%|                                                                                                             | 0/207 [00:00<?, ?it/s]

**Comment by Barigamb738** [comment]
fixed

**Comment by LISCARqaq** [comment]
@Barigamb738 Hi, how do you fix it? I got the same issue.

**Comment by Barigamb738** [comment]
I'm really sorry but I don't remember
