### ISSUE TITLE
Cant train

### ISSUE THREAD

**Issue by dillfrescott** [r9y9/wavenet_vocoder#220]
It just keeps saying:

```
/usr/local/lib/python3.7/dist-packages/nnmnkwii/datasets/__init__.py:124: UserWarning: No files are collected. You might have specified wrong data source.
  warn("No files are collected. You might have specified wrong data source.")
Traceback (most recent call last):
  File "train.py", line 1070, in <module>
    data_loaders = get_data_loaders(dump_root, speaker_id, test_shuffle=True)
  File "train.py", line 995, in get_data_loaders
    Mel[0].shape))
  File "/usr/local/lib/python3.7/dist-packages/nnmnkwii/datasets/__init__.py", line 146, in __getitem__
    paths = self.collected_files[idx]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by lanberGB** [comment]
Please make sure there are three subfolders named "eval", "train_no_dev" and "dev" under your dataset path (dump_root)
