### ISSUE TITLE
Out of Memory on Synthesis 

### ISSUE THREAD

**Issue by dyelax** [r9y9/wavenet_vocoder#37]
When running `python synthesis.py <model_checkpoint_path> <output_dir> --conditional <mel_path>` , I consistently run out of GPU memory about 4 minutes into synthesis. I have a GTX 1080Ti (11GB memory), and when I watch `nvidia-smi` while synthesis is running, the memory usage continually increases until it runs out. How much GPU memory is generally required to synthesize a clip?

For reference, here is the progress on `ljspeech-mel-00001.npy` before it failed most recently:
`33249/195328 [03:57<19:18, 139.90it/s`

**Comment by imdatsolak** [comment]
@dyelax : are you getting OOM from NVIDIA Cuda or are you running out of main RAM? I can't see anything in r9y9's code where it would run OOM on GPU, but rather a place where it could run out of memory on main RAM if the audio to be generated is too long.

I have just generated an audio of 240,000 frames (yours is 195,328) and I had no problems with GTX 1080 Ti (11GB). BUT: I have 128GB of RAM...

**Comment by dyelax** [comment]
It's definitely a CUDA memory issue. Here's the error I'm getting:

```
THCudaCheck FAIL file=/tmp/pip-yxt749na-build/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "synthesis.py", line 182, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 124, in wavegen
    log_scale_min=hparams.log_scale_min)
  File "/workspace/wavenet_vocoder/wavenet_vocoder/wavenet.py", line 335, in incremental_forward
    x, h = f.incremental_forward(x, ct, gt)
  File "/workspace/wavenet_vocoder/wavenet_vocoder/modules.py", line 125, in incremental_forward
    return self._forward(x, c, g, True)
  File "/workspace/wavenet_vocoder/wavenet_vocoder/modules.py", line 143, in _forward
    x = self.conv.incremental_forward(x)
  File "/opt/conda/lib/python3.6/site-packages/deepvoice3_pytorch/conv.py", line 40, in incremental_forward
    self.input_buffer[:, :-1, :] = self.input_buffer[:, 1:, :].clone()
RuntimeError: cuda runtime error (2) : out of memory at /tmp/pip-yxt749na-build/aten/src/THC/generic/THCStorage.cu:58
```

I have 16GB RAM, but again, this definitely seems like a GPU memory problem. Especially sice I can see the GPU memory climbing and hitting max in `nvidia-smi`. I'm using `--preset presets/ljspeech_mixture.json`, which should have a sample rate of 22050

**Comment by imdatsolak** [comment]
Hmm, we are using Python 3.5 and no Docker-images. The problem is that `.clone()` is actually copying data, you you might actually reach a limit. I never had the problem but, you are right, you might be running OOM in Cuda because of cloning the data too many times...
Try reducing samplerate to 16000 or even 12000 Hz, pre-process again and try with that.

Sorry that I can't help more...

**Comment by npuichigo** [comment]
@dyelax What about synthesizing on cpu? I think it may run faster.

**Comment by r9y9** [comment]
I'm not sure if I can write pytorch code that triggers OOM, without accessing low-level APIs of CUDA. Isn't it a GPU driver bug or pytorch bug?

**Comment by r9y9** [comment]
I'm curious to see a fix by @neverjoe.

**Comment by aleksas** [comment]
@dyelax Also try to restart server/computer and execute same command again and see if problem persists. Sometimes I run into similar problems after killing training process which seams to later cause memory allocation issues.

**Comment by azraelkuan** [comment]
I have checked the synthesis process, in the `wavenet.py`
https://github.com/r9y9/wavenet_vocoder/blob/4d5f68c8341eb1dad1307ada7d99c8059840ca64/wavenet_vocoder/wavenet.py#L355
the `x` is the type of `Variable` when we save it in the list, this will case the memory increase in the sample process.
so we should change this to 
`outputs += [x.cpu().data.numpy()]`
and change https://github.com/r9y9/wavenet_vocoder/blob/4d5f68c8341eb1dad1307ada7d99c8059840ca64/wavenet_vocoder/wavenet.py#L325
to 
```current_input=Variable(torch.from_numpy(current_input))```
```if next(self.parameters()).is_cuda:```
``` .    current_input=current_input.cuda()```

**Comment by butterl** [comment]
@azraelkuan  do you meet error  when changed to 
current_input=Variable(torch.from_numpy(current_input))

```
Traceback (most recent call last):
  File "synthesis.py", line 187, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 125, in wavegen
    log_scale_min=hparams.log_scale_min)
  File "D:\code\wavenet_vocoder-master\wavenet_vocoder\wavenet.py", line 326, in incremental_forward
    current_input = Variable(torch.from_numpy(current_input))
TypeError: expected np.ndarray (got Tensor)
```

**Comment by r9y9** [comment]
@azraelkuan 

> the x is the type of Variable when we save it in the list, this will case the memory increase in the sample process.
so we should change this to
outputs += [x.cpu().data.numpy()]
and change

Sorry for chiming in late.  I understand the memory usage increases in the sampling process but I don't think it triggers OOM unless you are trying to synthesis too long audio. I'm wondering CPU<->GPU data transform per-sample is inefficient, though I don't care the speed so much since it's already super slow.
