### ISSUE TITLE
preprocess error while  pip install -e ".[train]" OK on windows 7

### ISSUE THREAD

**Issue by butterl** [r9y9/wavenet_vocoder#53]
Hi r9y9, thanks for your work!

I only have a borrowed machine with windows 7 have 1060 GPU and I tried  pip install -e ".[train]"

after I finished the preprocess step pop some error

```
D:\code\wavenet_vocoder-master>python preprocess.py --preset=presets/ljspeech_mixture.json ljspeech ./LJSpeech-1.1/ training_data_ljspeech
C:\Users\butter\AppData\Local\Programs\Python\Python35\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype
from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Sampling frequency: 22050
Traceback (most recent call last):
  File "preprocess.py", line 59, in <module>
    mod = importlib.import_module(name)
  File "C:\Users\butter\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\code\wavenet_vocoder-master\ljspeech.py", line 12, in <module>
    from wavenet_vocoder.util import is_mulaw_quantize, is_mulaw, is_raw
  File "D:\code\wavenet_vocoder-master\wavenet_vocoder\__init__.py", line 6, in <module>
    from .wavenet import receptive_field_size, WaveNet
  File "D:\code\wavenet_vocoder-master\wavenet_vocoder\wavenet.py", line 7, in <module>
    import torch
  File "C:\Users\butter\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```

the pytroch I'm follow the [instruction](http://pytorch.org/) 
```
pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.0-cp35-cp35m-win_amd64.whl 
pip3 install torchvision
```

And for bandmat I download the code , build locally to solve -Wno-unused-but-set-variable issue 

Do you got any idea  how to got through this? pytroch seems install good
```
from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by butterl** [comment]
I solved it by reinstall the whole env with conda
